n1 = float(input('Digite uma nota: '))
n2 = float(input('Digite uma nota: '))
n3 = float(input('Digite uma nota: '))
q1 = float(input('Digite um peso 1: '))
q2 = float(input('Digite um peso 2: '))
q3 = float(input('Digite um peso 3: '))
s = ( n1*q1 + n2*q2 + n3*q3 )
print(f'A média ponderada das notas é de {s}')