n = input('digite algo: ')
print('o tipo primitivo desse valor é', type(n))
print('só tem espaços?', n.isspace())
print('é um numero?', n.isalpha())
print('está em maiúsculas?', n.islower())
print('está em minúsculo?', n.isupper())
print('está capitalizada?', n.capitalize())
